name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci-ubuntu:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: git submodule update --init

      - name: Build
        run: bash configure.sh

      - name: Tests
        run: ./bin/Debug/run_tests

  ci-windows:
    runs-on: windows-2022
    env:
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: git submodule update --init

      - name: Build
        run: .\configure.cmd

      - name: Tests
        run: bin\Debug\run_tests.exe
